// lint-staged configuration.
//
// Kept in a dedicated file (not package.json) so the Prettier task can
// exclude autogenerated lockfiles. lint-staged passes the staged file paths
// to the command explicitly, which bypasses `.prettierignore` — so a staged
// `pnpm-lock.yaml` matched by the `*.{…,yaml}` glob would otherwise be
// reformatted on commit. Lockfiles are produced by the package manager and
// must never be hand- or tool-edited.
const LOCKFILE = /(?:^|\/)(?:pnpm-lock\.yaml|package-lock\.json|yarn\.lock)$/;

export default {
  "*.{js,mjs,cjs,ts,tsx,jsx}": [
    "eslint --fix --max-warnings 0 --no-warn-ignored",
  ],
  "*.{js,mjs,cjs,ts,tsx,jsx,json,md,yml,yaml}": (files) => {
    const formattable = files.filter((file) => !LOCKFILE.test(file));
    return formattable.length > 0
      ? [`prettier --write ${formattable.join(" ")}`]
      : [];
  },
};
