name: Secret Scan

on:
  pull_request:
  push:
    branches: [main]

jobs:
  gitleaks:
    uses: rmartz/vercel-deploy-scripts/.github/workflows/secret-scan.yml@de0710f966399763440e4e4aa223282b8b456ad2 # v5.1.0
    with:
      config-path: .gitleaks.toml
      install-deps: true
    permissions:
      contents: read
      pull-requests: write
